name: Gohub DI

on:
  push:
    tags:
      - 'server-v*'
      - 'client-v*'
      - 'all-v*'

permissions:
  contents: read

jobs:
  deploy-server:
    if: startsWith(github.ref, 'refs/tags/server-v') || startsWith(github.ref, 'refs/tags/all-v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          cache: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        run: |
          make -C server build-prod
          docker build -t ${{ secrets.AWS_ECR_SERVER_REPOSITORY }}:latest -f server/Dockerfile server -q
          docker tag ${{ secrets.AWS_ECR_SERVER_REPOSITORY }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_SERVER_REPOSITORY}}:${{ steps.extract_version.outputs.VERSION }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_SERVER_REPOSITORY }}:${{ steps.extract_version.outputs.VERSION }}

      - name: Update Lambda Function Container Image
        run: |
          FUNCTION_NAME=${{ secrets.AWS_LAMBDA_SERVER_FUNC_NAME }}
          NEW_IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_SERVER_REPOSITORY }}:${{ steps.extract_version.outputs.VERSION }}"
          
          aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $NEW_IMAGE_URI -o json
        if: success()

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,workflow
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `'CI Build ${{ job.status }} for ${{ github.repository }}`,
              }]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
